# -*- coding: utf-8 -*-
"""documentAudio Programing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xb0SX46D696rdvNZjVcsmLlf836duK-B
"""

from dB import calc

def main():

    dB = float(input('Ingrese los dB_fs: '))
    BitDepth = float(input('Ingrese BitDepth: '))
    Frec_Muestro = float(input('Ingrese Frecuencia de Muestreo: '))
    Frec_signal = float(input('Ingrese Frecuencia de la senal periodica: '))
    duracion = float(input('Ingrese el tiempo de su senal: '))

    print(type(dB) , type(BitDepth) , type(Frec_Muestro) ,type(Frec_signal),type(duracion) )

    signal = calc(dB, BitDepth, Frec_Muestro, Frec_signal, duracion)
    Amplitud = signal.Amp()
    print('Amplitud = ', Amplitud)
    signal.graficador(signal.ProcesoSenal(Amplitud))


if __name__ == '__main__':
    main()